#!/usr/bin/env python
"""
Plot Phase Diagrams for Superfine JSON-format Simulation Data

This script creates phase diagrams from the JSON simulation data generated by:
- run_48species_1000reps_superfine_parallel.py (1000 reps, superfine 0.025 step)

The script processes the JSON data format with sc_list and cc_list structure
and applies vector decomposition analysis to create phase diagrams.

Output:
- Figure/PhaseDiagram/Fig_phase_diagram_48species_{n_reps}reps_superfine.svg
"""

from common_setup import *
from pathlib import Path
import json
import pandas as pd
import numpy as np
import argparse
from scipy.ndimage import gaussian_filter1d
import matplotlib.pyplot as plt


def create_phase_diagram_smooth(
    type_names,
    data1_set,
    data2_set,
    data3_set,
    custom_x_ticks=None,
    custom_x_labels=None,
    output_filename="../figure/Fig_phase_diagram.svg",
    smooth_sigma=2.0,
    plot_boundary=False,
    use_step=False,
    regime_lines=None,
):
    """
    Creates a stacked-filled area plot of three classes
    (Dominance, Mixing, Restructuring) across given type names.

    Args:
        smooth_sigma: Gaussian smoothing sigma (higher = smoother). Default 2.0. Set to 0 for no smoothing.
        plot_boundary: Whether to draw black boundary lines between regions.
        use_step: If True, use step='post' for discrete bar-like appearance (raw data).
                  If False, use smooth interpolation.
        regime_lines: List of (mu_value, x_index) tuples for drawing vertical regime separator lines.
    """
    n_types = len(type_names)

    # For step plot, need n_types + 1 for proper bar alignment
    if use_step:
        class1_fractions = np.zeros(n_types + 1)
        class2_fractions = np.zeros(n_types + 1)
        class3_fractions = np.zeros(n_types + 1)
    else:
        class1_fractions = np.zeros(n_types)
        class2_fractions = np.zeros(n_types)
        class3_fractions = np.zeros(n_types)

    # Import phase diagram colors from centralized COLORMAP
    from COLORMAP import get_phase_diagram_colors
    colors = get_phase_diagram_colors()  # [dominance, mixing, restructuring]

    for c_i, type_name in enumerate(type_names):
        class1_count = 0
        class2_count = 0
        class3_count = 0

        for j in range(len(data1_set[type_name])):
            # Get vector decomposition coefficients
            u = data1_set[type_name][j]
            v = data2_set[type_name][j]
            k = data3_set[type_name][j]

            # Transform to asymmetricity coordinates
            x, y = calculate_assymetricity(u, v, k)

            # Classify using asymmetricity-based boundaries
            ii = characterize_case(x, y)
            if ii == 0:
                class1_count += 1
            elif ii == 1:
                class2_count += 1
            else:
                class3_count += 1

        total = class1_count + class2_count + class3_count
        if total > 0:
            class1_fractions[c_i] = class1_count / total
            class2_fractions[c_i] = class2_count / total
            class3_fractions[c_i] = class3_count / total

    # Apply Gaussian smoothing with 'nearest' mode to preserve edge values
    # Only apply smoothing if not using step plot and sigma > 0
    if smooth_sigma > 0 and not use_step:
        class1_smooth = gaussian_filter1d(class1_fractions, sigma=smooth_sigma, mode='nearest')
        class2_smooth = gaussian_filter1d(class2_fractions, sigma=smooth_sigma, mode='nearest')
        class3_smooth = gaussian_filter1d(class3_fractions, sigma=smooth_sigma, mode='nearest')

        # Renormalize to ensure they sum to 1
        total_smooth = class1_smooth + class2_smooth + class3_smooth
        class1_fractions = class1_smooth / total_smooth
        class2_fractions = class2_smooth / total_smooth
        class3_fractions = class3_smooth / total_smooth

    mm = 1 / 25.4 * 72
    fig_width = 60 * mm
    fig_height = 60 * mm

    fig, ax1 = plt.subplots(figsize=(fig_width / 72, fig_height / 72), facecolor='w')

    if use_step:
        x_vals = np.arange(n_types + 1)
    else:
        x_vals = np.arange(n_types)

    # Use step='post' for discrete bars, or smooth fill_between
    if use_step:
        fill1 = ax1.fill_between(
            x_vals, 0, class1_fractions,
            step='post', color=colors[0], alpha=0.85, edgecolor='none'
        )
        fill2 = ax1.fill_between(
            x_vals, class1_fractions, class1_fractions + class2_fractions,
            step='post', color=colors[1], alpha=0.85, edgecolor='none'
        )
        fill3 = ax1.fill_between(
            x_vals, class1_fractions + class2_fractions,
            class1_fractions + class2_fractions + class3_fractions,
            step='post', color=colors[2], alpha=0.85, edgecolor='none'
        )
    else:
        fill1 = ax1.fill_between(
            x_vals, 0, class1_fractions,
            color=colors[0], alpha=0.85, edgecolor='none'
        )
        fill2 = ax1.fill_between(
            x_vals, class1_fractions, class1_fractions + class2_fractions,
            color=colors[1], alpha=0.85, edgecolor='none'
        )
        fill3 = ax1.fill_between(
            x_vals, class1_fractions + class2_fractions,
            class1_fractions + class2_fractions + class3_fractions,
            color=colors[2], alpha=0.85, edgecolor='none'
        )

    # Plot boundary lines between regions
    if plot_boundary:
        # Boundary between dominance (bottom) and restructuring (middle)
        ax1.plot(x_vals, class1_fractions, color='black', linewidth=0.8, linestyle='-')
        # Boundary between restructuring (middle) and mixing (top)
        ax1.plot(x_vals, class1_fractions + class2_fractions, color='black', linewidth=0.8, linestyle='-')

    # Plot vertical regime separator lines
    if regime_lines is not None:
        for x_pos in regime_lines:
            ax1.axvline(x=x_pos, color='black', linewidth=1.5, linestyle='-', alpha=0.4)

    ax1.set_xlim(0, n_types - 1)
    ax1.set_ylim(0, 1)

    if custom_x_ticks is not None and custom_x_labels is not None:
        ax1.set_xticks(custom_x_ticks)
        ax1.set_xticklabels(custom_x_labels)

    ax1.set_xlabel(r'Interaction Strength $\mu$')
    ax1.set_ylabel('Fraction')

    ax1.tick_params(axis='both', which='major', labelsize=6, width=0.5, length=3.5, direction='out', color='#262626', labelcolor='#262626')
    for spine in ax1.spines.values():
        spine.set_linewidth(0.5)
        spine.set_color('#262626')

    plt.tight_layout()
    fig.savefig(output_filename, format='svg', dpi=300, transparent=False)
    # Also save as PDF
    pdf_filename = output_filename.replace('.svg', '.pdf')
    fig.savefig(pdf_filename, format='pdf', dpi=300, transparent=False)
    plt.close(fig)

def process_json_simulation_data(json_file_path, session_name):
    """
    Process JSON simulation data and extract vector decomposition coefficients.

    Parameters:
    json_file_path: Path to the JSON file with simulation data
    session_name: Name of the simulation session

    Returns:
    types_to_plot: List of u-values (interaction strengths)
    data1: Parent1 coefficients
    data2: Parent2 coefficients
    data3: Residual magnitudes
    """

    print(f"Processing JSON simulation data: {session_name}")

    if not Path(json_file_path).exists():
        print(f"Warning: File not found: {json_file_path}")
        return None, None, None, None

    try:
        # Load JSON data
        with open(json_file_path, 'r') as f:
            simulation_data = json.load(f)

        print(f"Loaded JSON data with {len(simulation_data)} interaction strengths")

        # Initialize data structures
        types_to_plot = []
        data1 = {}  # Parent1 coefficients
        data2 = {}  # Parent2 coefficients
        data3 = {}  # Residual magnitudes

        # Process each interaction strength
        for u_str, u_data in simulation_data.items():
            if len(u_data) == 0:
                print(f"  Skipping u = {u_str} (no data)")
                continue

            types_to_plot.append(u_str)

            # Initialize lists for this u-value
            u_data1 = []  # Parent1 coefficients
            u_data2 = []  # Parent2 coefficients
            u_data3 = []  # Residual magnitudes

            # Process each repetition
            processed_reps = 0
            for rep_key, rep_data in u_data.items():
                try:
                    # Get single communities and coalescence results
                    sc_list = rep_data.get('sc_list', {})
                    cc_list = rep_data.get('cc_list', {})

                    if not sc_list or not cc_list:
                        continue

                    # Process each coalescence pair
                    for cc_key, cmix in cc_list.items():
                        # Parse coalescence key (format: "0_1", "0_2", etc.)
                        try:
                            c1_idx, c2_idx = cc_key.split('_')
                            c1_idx, c2_idx = int(c1_idx), int(c2_idx)
                        except:
                            continue

                        # Get parent community data
                        if str(c1_idx) not in sc_list or str(c2_idx) not in sc_list:
                            # Try with integer key (parallel version uses int keys)
                            if c1_idx not in sc_list or c2_idx not in sc_list:
                                continue
                            c1 = np.array(sc_list[c1_idx])
                            c2 = np.array(sc_list[c2_idx])
                        else:
                            c1 = np.array(sc_list[str(c1_idx)])
                            c2 = np.array(sc_list[str(c2_idx)])

                        cmix = np.array(cmix)

                        # Apply vector decomposition
                        try:
                            u_coeff, v_coeff, k_coeff = metric_VectorDecomposition_onlyPositive(c1, c2, cmix)

                            # Store coefficients
                            u_data1.append(u_coeff)
                            u_data2.append(v_coeff)
                            u_data3.append(k_coeff)

                        except Exception as decomp_error:
                            # Handle singular matrix or other decomposition errors
                            continue

                    processed_reps += 1

                except Exception as rep_error:
                    continue

            # Store data for this u-value
            data1[u_str] = u_data1
            data2[u_str] = u_data2
            data3[u_str] = u_data3

            print(f"  u = {u_str}: {processed_reps} reps, {len(u_data1)} coalescence events")

        print(f"Successfully processed {len(types_to_plot)} interaction strengths")

        # Sort by numerical u-value for proper ordering
        try:
            types_to_plot.sort(key=lambda x: float(x))
        except:
            types_to_plot.sort()  # fallback to string sort

        return types_to_plot, data1, data2, data3

    except Exception as e:
        print(f"Error processing {json_file_path}: {e}")
        import traceback
        traceback.print_exc()
        return None, None, None, None


def plot_superfine_phase_diagram(n_reps=50, step_size=0.025, smooth_sigma=2.0):
    """Generate phase diagram for superfine simulation data.

    Generates both smoothed and non-smoothed versions.
    """

    print(f"Generating phase diagrams for superfine simulation data ({n_reps} reps, step={step_size})...")
    print("Using colormap: Red (Dominance), Purple (Mixing), Green (Restructuring)")

    # Determine JSON file path
    json_file = f"Simulation_Data/48species_{n_reps}reps_superfine/Community_{n_reps}reps_superfine.json"
    session_name = f"48species_{n_reps}reps_superfine"

    print(f"\n{'='*60}")
    print(f"Processing {session_name}")
    print(f"JSON file: {json_file}")
    print(f"{'='*60}")

    # Check if file exists
    if not Path(json_file).exists():
        print(f"Error: JSON file not found: {json_file}")
        return False

    # Process the JSON simulation data
    types_to_plot, data1, data2, data3 = process_json_simulation_data(
        json_file, session_name
    )

    if types_to_plot is None or len(types_to_plot) == 0:
        print(f"Skipping {session_name} due to data processing error or no data")
        return False

    # Use actual keys from the data (already sorted in types_to_plot)
    # The keys are formatted as f"{u:.2f}" which may differ from exact step values
    n_values = len(types_to_plot)

    print(f"Found {n_values} u-values in data")
    print(f"Range: {types_to_plot[0]} to {types_to_plot[-1]}")

    # Show custom tick labels: 0.4, 0.8, 1.2
    # Find positions closest to target values
    custom_x_ticks = []
    custom_x_labels = []

    target_labels = [0.4, 0.8, 1.2]
    for target in target_labels:
        # Find the closest key to the target
        closest_idx = min(range(len(types_to_plot)),
                        key=lambda i: abs(float(types_to_plot[i]) - target))
        custom_x_ticks.append(closest_idx)
        custom_x_labels.append(f"{target:.1f}")

    # Use the actual data directly (no padding needed since we use actual keys)
    plot_types = types_to_plot
    plot_data1, plot_data2, plot_data3 = data1, data2, data3

    # Calculate regime line positions for mu = 0.3, 0.6, 0.8
    regime_mu_values = [0.3, 0.6, 0.8]
    regime_line_positions = []
    for target_mu in regime_mu_values:
        # Find the closest key to the target mu value
        closest_idx = min(range(len(types_to_plot)),
                        key=lambda i: abs(float(types_to_plot[i]) - target_mu))
        regime_line_positions.append(closest_idx)
    print(f"Regime line positions (mu={regime_mu_values}): {regime_line_positions}")

    # Ensure output directory exists
    Path("Figure/PhaseDiagram").mkdir(parents=True, exist_ok=True)

    try:
        # Generate NON-SMOOTHED version with step (bar) plot
        output_filename_raw = f"Figure/PhaseDiagram/Fig_phase_diagram_{session_name}_raw.svg"
        create_phase_diagram_smooth(
            plot_types,
            plot_data1, plot_data2, plot_data3,
            custom_x_ticks,
            custom_x_labels,
            output_filename=output_filename_raw,
            smooth_sigma=0,
            plot_boundary=False,
            use_step=True,  # Use discrete bar-like step plot
            regime_lines=regime_line_positions
        )
        print(f"\nCreated (raw step plot): {output_filename_raw}")

        # Generate SMOOTHED version with smooth interpolation
        output_filename_smooth = f"Figure/PhaseDiagram/Fig_phase_diagram_{session_name}_smooth.svg"
        create_phase_diagram_smooth(
            plot_types,
            plot_data1, plot_data2, plot_data3,
            custom_x_ticks,
            custom_x_labels,
            output_filename=output_filename_smooth,
            smooth_sigma=smooth_sigma,
            plot_boundary=False,
            use_step=False,  # Use smooth interpolation
            regime_lines=regime_line_positions
        )
        print(f"Created (smoothed sigma={smooth_sigma}): {output_filename_smooth}")

        # Print statistics about the data
        total_points = sum(len(data1.get(t, [])) for t in types_to_plot)
        print(f"\nData points processed: {total_points}")

        # Print summary breakdown
        print(f"\nSummary by interaction strength range:")
        ranges = [(0.05, 0.4), (0.4, 0.8), (0.8, 1.2)]
        for low, high in ranges:
            range_points = sum(len(data1.get(t, [])) for t in types_to_plot
                             if low <= float(t) < high)
            print(f"  u in [{low:.2f}, {high:.2f}): {range_points} events")

        return True

    except Exception as e:
        print(f"Failed to create phase diagrams: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    """Main function to run the phase diagram generation."""

    parser = argparse.ArgumentParser(description='Plot phase diagram for superfine simulation data')
    parser.add_argument('--n_reps', type=int, default=50,
                        help='Number of repetitions (default: 50)')
    parser.add_argument('--step', type=float, default=0.025,
                        help='Interaction strength step size (default: 0.025)')
    parser.add_argument('--smooth', type=float, default=2.0,
                        help='Gaussian smoothing sigma (default: 2.0, 0 for no smoothing)')
    args = parser.parse_args()

    success = plot_superfine_phase_diagram(n_reps=args.n_reps, step_size=args.step, smooth_sigma=args.smooth)

    if success:
        print(f"\n{'='*60}")
        print("PHASE DIAGRAM GENERATION COMPLETE!")
        print(f"{'='*60}")
        print(f"Output directory: Figure/PhaseDiagram/")
    else:
        print(f"\n{'='*60}")
        print("PHASE DIAGRAM GENERATION FAILED!")
        print(f"{'='*60}")


if __name__ == "__main__":
    main()
