#!/usr/bin/env python
"""
Script to show summary of the standard simulation data
"""

import pandas as pd
import numpy as np
import os

def show_data_summary():
    """Show summary of standard simulation data"""
    
    data_dir = "Simulation_Data/standard"
    
    print("STANDARD SIMULATION DATA SUMMARY")
    print("=" * 50)
    print(f"📁 Data Directory: {data_dir}")
    print()
    
    # Check if directory exists
    if not os.path.exists(data_dir):
        print("❌ Standard data directory not found!")
        return
    
    # List files
    files = os.listdir(data_dir)
    print(f"📄 Files in directory:")
    for file in sorted(files):
        file_path = os.path.join(data_dir, file)
        size = os.path.getsize(file_path)
        print(f"  • {file} ({size:,} bytes)")
    print()
    
    # Read and summarize main data file
    similarity_file = os.path.join(data_dir, "Similarity.xlsx")
    if os.path.exists(similarity_file):
        print("📊 SIMILARITY.XLSX CONTENT:")
        print("-" * 30)
        
        try:
            # Read all sheets
            xl_file = pd.ExcelFile(similarity_file)
            print(f"📑 Number of sheets: {len(xl_file.sheet_names)}")
            print(f"📑 Sheet names: {xl_file.sheet_names}")
            print()
            
            # Read first sheet (parent1 coefficients)
            sheet1 = pd.read_excel(similarity_file, sheet_name=0)
            print(f"📋 Sheet 1 (Parent1 coefficients):")
            print(f"   Shape: {sheet1.shape}")
            print(f"   Columns: {list(sheet1.columns)}")
            print(f"   Sample data (first 5 rows, first 3 columns):")
            print(sheet1.iloc[:5, :3].to_string())
            print()
            
            # Show interaction strength range
            u_columns = [col for col in sheet1.columns if col.startswith('u_')]
            if u_columns:
                u_values = [float(col.replace('u_', '')) for col in u_columns]
                print(f"🎯 Interaction strengths (u-values): {sorted(u_values)}")
                print(f"   Range: {min(u_values):.1f} to {max(u_values):.1f}")
                print(f"   Number of u-values: {len(u_values)}")
                
                # Show number of data points per u-value
                sample_col = u_columns[0]
                non_nan_count = sheet1[sample_col].notna().sum()
                print(f"   Repetitions per u-value: {non_nan_count}")
                print()
        
        except Exception as e:
            print(f"❌ Error reading Similarity.xlsx: {e}")
    
    # Read parameters
    param_file = os.path.join(data_dir, "parameter.xlsx")
    if os.path.exists(param_file):
        print("⚙️  PARAMETERS:")
        print("-" * 15)
        try:
            params = pd.read_excel(param_file)
            for col in params.columns:
                value = params[col].iloc[0]
                print(f"   {col}: {value}")
        except Exception as e:
            print(f"❌ Error reading parameter.xlsx: {e}")
    
    print()
    print("✅ This data was generated by: run_standard_simulation_100reps_simple.py")
    print("🎯 Used by: plot_phase_diagram_simulation.py → Fig_phase_diagram_Simul_standard.svg")

if __name__ == "__main__":
    show_data_summary()