#!/usr/bin/env python3
"""
Build the pH/growth-rate workbook for Jiliang.

Inputs used here are the processed tables generated by the existing MATLAB
pipeline plus the raw isolate pH/OD plate exports used by the figure code.
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pandas as pd
from openpyxl.chart import BarChart, Reference
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = Path(__file__).resolve().parent
OUT_XLSX = OUT_DIR / "To_Jiliang_pH_growth_20260517.xlsx"

COMMUNITY_METADATA = ROOT / "Postprocessed" / "Metadata.xlsx"
ISOLATE_METADATA = ROOT / "Postprocessed" / "Metadata_Isolates.xlsx"
ISOLATE_PH = (
    ROOT
    / "ExperimentalResult"
    / "Data"
    / "2208_Coalescence_processed"
    / "pH_isolates"
    / "230623_pH.xlsx"
)
ISOLATE_OD = (
    ROOT
    / "ExperimentalResult"
    / "Data"
    / "2208_Coalescence_processed"
    / "pH_isolates"
    / "220910_54isolatesOD_flat100um.xlsx"
)

MEDIUM_LABELS = {
    "L": "Nutr- / LN",
    "M": "Base / MN",
    "H": "Nutr+ / HN",
    "LN": "Nutr- / LN",
    "MN": "Base / MN",
    "HN": "Nutr+ / HN",
}
ORIGIN_LABELS = {"S": "synthetic", "N": "natural"}
TYPE_LABELS = {"S": "single_community", "C": "coalesced_community"}
RICHNESS_BY_SYNTHETIC_COMMUNITY_INDEX = (
    (1, 9, "6_species"),
    (10, 18, "12_species"),
    (19, 30, "24_species"),
)


def clean_numeric(value):
    """Convert plate-reader cells such as '48?' to numbers and blanks to NaN."""
    if pd.isna(value):
        return np.nan
    if isinstance(value, (int, float, np.integer, np.floating)):
        return float(value)
    match = re.search(r"-?\d+(?:\.\d+)?", str(value))
    return float(match.group(0)) if match else np.nan


def synthetic_richness(row: pd.Series) -> str:
    if row["community_origin_code"] != "S" or row["sample_type_code"] != "S":
        return ""
    idx = int(row["community_index"])
    for lo, hi, label in RICHNESS_BY_SYNTHETIC_COMMUNITY_INDEX:
        if lo <= idx <= hi:
            return label
    return ""


def load_community_samples() -> pd.DataFrame:
    raw = pd.read_excel(COMMUNITY_METADATA)
    od_cols = [f"fieldOD{i}" for i in range(1, 8)]
    ph_cols = [f"fieldPH{i}" for i in range(1, 8)]
    gc_cols = [f"fieldGC{i}" for i in range(1, 4)]

    df = raw.rename(
        columns={
            "SampleIDX": "sample_id",
            "IDX": "pair_index",
            "CommunityOrigin": "community_origin_code",
            "Medium": "medium_code",
            "CoalescenceType": "sample_type_code",
            "Replicate": "replicate",
            "CommunityIDX": "community_index",
            "fieldGC1": "growth_rate_expfit_h_inv",
            "fieldGC2": "growth_rate_15x_min_h_inv",
            "fieldGC3": "growth_rate_halfmax_h_inv",
        }
    ).copy()

    df["community_origin"] = df["community_origin_code"].map(ORIGIN_LABELS)
    df["medium"] = df["medium_code"].map(MEDIUM_LABELS)
    df["sample_type"] = df["sample_type_code"].map(TYPE_LABELS)
    df["synthetic_parent_richness"] = df.apply(synthetic_richness, axis=1)

    for i in range(1, 8):
        df[f"OD_day{i}"] = raw[f"fieldOD{i}"]
        df[f"pH_day{i}"] = raw[f"fieldPH{i}"]

    df["pH_day7_minus_day1"] = df["pH_day7"] - df["pH_day1"]
    df["pH_mean_day5_to_day7"] = df[["pH_day5", "pH_day6", "pH_day7"]].mean(axis=1)
    df["pH_range_day5_to_day7"] = df[["pH_day5", "pH_day6", "pH_day7"]].max(axis=1) - df[
        ["pH_day5", "pH_day6", "pH_day7"]
    ].min(axis=1)
    df["OD_day7_minus_day1"] = df["OD_day7"] - df["OD_day1"]
    df["OD_mean_day5_to_day7"] = df[["OD_day5", "OD_day6", "OD_day7"]].mean(axis=1)
    df["max_endpoint_OD_day1_to_day7"] = df[[f"OD_day{i}" for i in range(1, 8)]].max(axis=1)

    ordered = [
        "sample_id",
        "pair_index",
        "community_origin",
        "medium",
        "sample_type",
        "replicate",
        "community_index",
        "synthetic_parent_richness",
        "pH_day1",
        "pH_day2",
        "pH_day3",
        "pH_day4",
        "pH_day5",
        "pH_day6",
        "pH_day7",
        "pH_day7_minus_day1",
        "pH_mean_day5_to_day7",
        "pH_range_day5_to_day7",
        "OD_day1",
        "OD_day2",
        "OD_day3",
        "OD_day4",
        "OD_day5",
        "OD_day6",
        "OD_day7",
        "OD_day7_minus_day1",
        "OD_mean_day5_to_day7",
        "max_endpoint_OD_day1_to_day7",
        "growth_rate_expfit_h_inv",
        "growth_rate_15x_min_h_inv",
        "growth_rate_halfmax_h_inv",
    ]
    return df[ordered]


def summarize_communities(samples: pd.DataFrame) -> pd.DataFrame:
    metrics = [
        "pH_day1",
        "pH_day7",
        "pH_day7_minus_day1",
        "pH_mean_day5_to_day7",
        "OD_day7",
        "max_endpoint_OD_day1_to_day7",
        "growth_rate_expfit_h_inv",
        "growth_rate_15x_min_h_inv",
        "growth_rate_halfmax_h_inv",
    ]
    group_cols = ["community_origin", "medium", "sample_type"]
    summary = samples.groupby(group_cols, dropna=False)[metrics].agg(["count", "mean", "std", "median"])
    summary.columns = ["_".join(col).strip() for col in summary.columns.to_flat_index()]
    return summary.reset_index()


def compare_single_vs_coalesced(summary: pd.DataFrame) -> pd.DataFrame:
    mean_cols = [c for c in summary.columns if c.endswith("_mean")]
    long = summary[["community_origin", "medium", "sample_type", *mean_cols]].copy()
    rows = []
    for (origin, medium), sub in long.groupby(["community_origin", "medium"]):
        by_type = sub.set_index("sample_type")
        if {"single_community", "coalesced_community"}.issubset(by_type.index):
            row = {"community_origin": origin, "medium": medium}
            for col in mean_cols:
                sc = by_type.loc["single_community", col]
                cc = by_type.loc["coalesced_community", col]
                metric = col.removesuffix("_mean")
                row[f"{metric}_SC_mean"] = sc
                row[f"{metric}_CC_mean"] = cc
                row[f"{metric}_CC_minus_SC"] = cc - sc
            rows.append(row)
    return pd.DataFrame(rows)


def find_plate_data_start(df: pd.DataFrame) -> int:
    for i in range(len(df)):
        if str(df.iloc[i, 0]).strip() == "A":
            return i
    raise ValueError("Could not find plate row A in Excel sheet.")


def load_plate_values(path: Path, sheet: str, value_name: str, scale: float = 1.0) -> pd.DataFrame:
    raw = pd.read_excel(path, sheet_name=sheet, header=None)
    start = find_plate_data_start(raw)
    rows = []
    for r, row_label in enumerate(list("ABCDEFGH")):
        if start + r >= len(raw):
            break
        for c in range(1, 13):
            value = clean_numeric(raw.iloc[start + r, c])
            if np.isfinite(value):
                rows.append(
                    {
                        "well": f"{row_label}{c}",
                        "plate_row": row_label,
                        "plate_col": c,
                        value_name: value / scale,
                    }
                )
    out = pd.DataFrame(rows)
    out["isolate_order"] = np.arange(1, len(out) + 1)
    return out


def load_monoculture_isolates() -> pd.DataFrame:
    growth = pd.read_excel(ISOLATE_METADATA).head(54).copy()
    growth["isolate_order"] = np.arange(1, len(growth) + 1)
    growth["isolate_id"] = growth["isolate_order"].map(lambda x: f"isolate_{x:02d}")
    growth["well_growth_plate_order"] = [
        f"{row}{col}" for row in list("ABCDEF") for col in range(1, 10)
    ][: len(growth)]

    rename = {
        "LN_O1": "LN_growth_rate_expfit_h_inv",
        "LN_O2": "LN_growth_rate_15x_min_h_inv",
        "LN_O3": "LN_growth_rate_halfmax_h_inv",
        "LN_O4": "LN_max_growth_curve_OD",
        "MN_O1": "MN_growth_rate_expfit_h_inv",
        "MN_O2": "MN_growth_rate_15x_min_h_inv",
        "MN_O3": "MN_growth_rate_halfmax_h_inv",
        "MN_O4": "MN_max_growth_curve_OD",
        "HN_O1": "HN_growth_rate_expfit_h_inv",
        "HN_O2": "HN_growth_rate_15x_min_h_inv",
        "HN_O3": "HN_growth_rate_halfmax_h_inv",
        "HN_O4": "HN_max_growth_curve_OD",
    }
    growth = growth.rename(columns=rename)
    metric_cols = list(rename.values())
    for col in metric_cols:
        growth[col] = pd.to_numeric(growth[col], errors="coerce")
        growth.loc[growth[col] > 100, col] = np.nan

    ph = load_plate_values(ISOLATE_PH, "after 15h", "monoculture_pH_after_15h", scale=10.0)
    od = load_plate_values(ISOLATE_OD, "Sheet4", "monoculture_endpoint_OD", scale=1.0)

    # The existing figure code used plate order and then truncated to the 54-isolate library.
    ph = ph.head(54).rename(columns={"well": "well_pH_plate"})
    od = od.head(54).rename(columns={"well": "well_OD_plate"})
    out = growth.merge(ph[["isolate_order", "well_pH_plate", "monoculture_pH_after_15h"]], on="isolate_order", how="left")
    out = out.merge(od[["isolate_order", "well_OD_plate", "monoculture_endpoint_OD"]], on="isolate_order", how="left")

    out["pH_after_15h_minus_start_6p5"] = out["monoculture_pH_after_15h"] - 6.5

    front = [
        "isolate_order",
        "isolate_id",
        "well_growth_plate_order",
        "well_pH_plate",
        "well_OD_plate",
        "monoculture_pH_after_15h",
        "pH_after_15h_minus_start_6p5",
        "monoculture_endpoint_OD",
    ]
    return out[front + metric_cols]


def summarize_monocultures(isolates: pd.DataFrame) -> pd.DataFrame:
    rows = []
    base_metrics = ["monoculture_pH_after_15h", "pH_after_15h_minus_start_6p5", "monoculture_endpoint_OD"]
    for metric in base_metrics:
        s = isolates[metric].dropna()
        rows.append({"group": "all_isolates", "metric": metric, "n": len(s), "mean": s.mean(), "std": s.std(), "median": s.median(), "min": s.min(), "max": s.max()})

    for medium in ["LN", "MN", "HN"]:
        for metric_suffix in [
            "growth_rate_expfit_h_inv",
            "growth_rate_15x_min_h_inv",
            "growth_rate_halfmax_h_inv",
            "max_growth_curve_OD",
        ]:
            metric = f"{medium}_{metric_suffix}"
            s = isolates[metric].dropna()
            rows.append(
                {
                    "group": MEDIUM_LABELS[medium],
                    "metric": metric_suffix,
                    "n": len(s),
                    "mean": s.mean(),
                    "std": s.std(),
                    "median": s.median(),
                    "min": s.min(),
                    "max": s.max(),
                }
            )
    return pd.DataFrame(rows)


def source_notes() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "item": "Community pH/OD/growth data",
                "source": str(COMMUNITY_METADATA.relative_to(ROOT)),
                "notes": "Generated by ExperimentalResult/ExperimentalDataProcessing.m. pH and OD are day1-day7 endpoint readings; growth columns are GRcalculate.m outputs.",
            },
            {
                "item": "Monoculture isolate growth data",
                "source": str(ISOLATE_METADATA.relative_to(ROOT)),
                "notes": "Generated by ExperimentalResult/IsolateExperimentalDataProcessing.m. O1/O2/O3 are GRcalculate_500.m growth-rate metrics; O4 is max OD from the growth curve.",
            },
            {
                "item": "Monoculture isolate pH",
                "source": str(ISOLATE_PH.relative_to(ROOT)),
                "notes": "Raw plate-reader pH values after 15h; values are stored as pH x 10 and divided by 10 here.",
            },
            {
                "item": "Monoculture endpoint OD",
                "source": str(ISOLATE_OD.relative_to(ROOT)),
                "notes": "Raw plate-reader OD values from Sheet4, matching the existing monoculture histogram code.",
            },
        ]
    )


def add_formatting(writer: pd.ExcelWriter) -> None:
    wb = writer.book
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_font = Font(color="FFFFFF", bold=True)

    for ws in wb.worksheets:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions
        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        for column_cells in ws.columns:
            letter = get_column_letter(column_cells[0].column)
            max_len = max(len(str(cell.value)) if cell.value is not None else 0 for cell in column_cells[:200])
            ws.column_dimensions[letter].width = min(max(max_len + 2, 10), 35)
        for row in ws.iter_rows(min_row=2):
            for cell in row:
                if isinstance(cell.value, float):
                    cell.number_format = "0.000"

    if "SC_vs_CC" in wb.sheetnames:
        ws = wb["SC_vs_CC"]
        chart = BarChart()
        chart.type = "col"
        chart.style = 10
        chart.title = "Mean pH day7: SC vs CC"
        chart.y_axis.title = "pH"
        chart.x_axis.title = "origin + medium"
        headers = [cell.value for cell in ws[1]]
        try:
            sc_col = headers.index("pH_day7_SC_mean") + 1
            cc_col = headers.index("pH_day7_CC_mean") + 1
            data = Reference(ws, min_col=sc_col, max_col=cc_col, min_row=1, max_row=ws.max_row)
            cats = Reference(ws, min_col=2, min_row=2, max_row=ws.max_row)
            chart.add_data(data, titles_from_data=True)
            chart.set_categories(cats)
            chart.height = 7
            chart.width = 14
            ws.add_chart(chart, "B10")
        except ValueError:
            pass


def main() -> None:
    community_samples = load_community_samples()
    community_summary = summarize_communities(community_samples)
    sc_vs_cc = compare_single_vs_coalesced(community_summary)
    monoculture_isolates = load_monoculture_isolates()
    monoculture_summary = summarize_monocultures(monoculture_isolates)

    with pd.ExcelWriter(OUT_XLSX, engine="openpyxl") as writer:
        source_notes().to_excel(writer, sheet_name="sources", index=False)
        community_samples.to_excel(writer, sheet_name="community_samples", index=False)
        community_summary.to_excel(writer, sheet_name="community_summary", index=False)
        sc_vs_cc.to_excel(writer, sheet_name="SC_vs_CC", index=False)
        monoculture_isolates.to_excel(writer, sheet_name="monoculture_isolates", index=False)
        monoculture_summary.to_excel(writer, sheet_name="monoculture_summary", index=False)
        add_formatting(writer)

    print(f"Wrote {OUT_XLSX}")
    print(f"community_samples: {len(community_samples)} rows")
    print(f"monoculture_isolates: {len(monoculture_isolates)} rows")


if __name__ == "__main__":
    main()
